import { usePortfolio } from '../../src/hooks/PortfolioContext';
import { APP_SETTINGS, DEFAULT_USER } from '../../src/config/env';

const Footer = () => {
  const { portfolio } = usePortfolio();
  const name = portfolio?.personalInfo?.name || DEFAULT_USER.NAME;

  return (
    <footer className="max-w-md pb-16 sm:pb-0">
      <p className="t2-meta leading-relaxed">
        Designed in the margins and built with React and Tailwind. Set in{' '}
        <span className="t2-serif italic text-foreground/80">Fraunces</span>, Inter and IBM Plex Mono. Content regenerated by{' '}
        <span className="text-foreground/80">{APP_SETTINGS.APP_NAME}</span> from resume and GitHub data.
      </p>
      <p className="t2-meta mt-3">
        © {new Date().getFullYear()} {name}
      </p>
    </footer>
  );
};

export default Footer;
